insert into "user" (id, name, surname, email, password, status) values (default, 'Tadeo', 'Cawthery', 'tcawthery0@behance.net', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Cara', 'Sabin', 'csabin1@amazon.de', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Maisie', 'Peepall', 'nikolaakv@gmail.com', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Ruggiero', 'Boij', 'rboij3@imgur.com', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Caz', 'Gavrieli', 'cgavrieli4@woothemes.com', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Correy', 'Klimentyonok', 'cklimentyonok5@businessinsider.com', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Doloritas', 'Bonafacino', 'dbonafacino6@mapy.cz', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Lu', 'Uren', 'luren7@nhs.uk', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Talyah', 'Czaja', 'tczaja8@networksolutions.com', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
insert into "user" (id, name, surname, email, password, status) values (default, 'Dalston', 'MacCartan', 'dmaccartan9@so-net.ne.jp', '$2a$10$.r4El/SxWktyti7tzqKnDuv.nAZGW2XK6mD5lZZYxMSQsdF.uMWRq', 'VERIFIED');
--All passwords are 123123