insert into "member" (id_user, id_group) values (2, 5);
insert into "member" (id_user, id_group) values (3, 2);
insert into "member" (id_user, id_group) values (5, 7);
insert into "member" (id_user, id_group) values (1, 1);
insert into "member" (id_user, id_group) values (1, 2);
insert into "member" (id_user, id_group) values (2, 1);
insert into "member" (id_user, id_group) values (2, 3);
insert into "member" (id_user, id_group) values (3, 3);
insert into "member" (id_user, id_group) values (5, 9);
