CREATE TABLE "post" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "private" boolean,
    "text" varchar,
    "created_date" timestamp,
    "deleted" boolean,
    "id_user" bigint,
    "id_group" bigint
);