CREATE TABLE "Comment" (
   "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
   "text" varchar,
   "createdDate" timestamp,
   "deleted" boolean,
   "id_user" bigint,
   "id_replied_to" bigint,
   "id_post" bigint
);