CREATE TABLE "event" (
     "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     "id_location" bigint,
     "start_date" timestamp,
     "end_date" timestamp,
     "id_user" bigint,
     "id_group" bigint
);